# Generated by Django 2.0.3 on 2018-03-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmailuser',
            name='password',
        ),
    ]
