# Generated by Django 2.0.3 on 2018-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmail', '0002_remove_vmailuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmailuser',
            name='password',
            field=models.CharField(default='evnk', max_length=200),
            preserve_default=False,
        ),
    ]
