# Generated by Django 2.0.3 on 2018-03-31 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmail', '0003_vmailuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmailuser',
            options={'verbose_name_plural': 'vmailusers'},
        ),
        migrations.AddField(
            model_name='vmailuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
