# Generated by Django 2.0.3 on 2018-03-31 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmail', '0004_auto_20180331_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
            ],
        ),
    ]
