# Generated by Django 2.0.3 on 2018-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmail', '0006_vmails_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmailuser',
            name='login',
            field=models.IntegerField(default=0),
        ),
    ]
